name: My First Workflow
on: push

jobs:
 my-frist-job:
    runs-on: ubuntu-latest
    env:
     USER: "boss is back"
    steps:
      - run: echo ${{github.token}}
      - run: echo ${{secrets.GITHUB_TOKEN}}
      - run: echo "$USER"


